### PR TITLE
Feature/ar/basic ar

### PR DESCRIPTION
**Pull request by Hanker00**

### CODE REVIEW

**Comment by axelsoderberg** [comment]
AR should now be at least displayable. The user needs to be within 50 meters and point their device within a 60 degree span towards the flag for AR view to launch. The code is very ugly, has a lot of redundancy, but these can be fixed later.

**Review by sallishsh — APPROVED** [review]
LGTM.

**Review by sallishsh — CHANGES_REQUESTED** [review]
Remove all chicken things

**Review by sallishsh — APPROVED** [review]
LGTM

**Pull request merged**
